name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '38 13 * * 0'

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        include:
        - os: ubuntu-18.04
          build-mode: manual
        - os: windows-latest
          build-mode: manual
        - os: macos-latest
          build-mode: manual

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Dependencies on Ubuntu
      if: matrix.os == 'ubuntu-18.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev libboost-test-dev libboost-thread-dev libfmt-dev libsqlite3-dev libminiupnpc-dev libzmq3-dev libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libqrencode-dev g++-mingw-w64-x86-64 nsis
        ./contrib/install_db4.sh $(pwd)
        export BDB_PREFIX=$(pwd)/db4
        echo "BDB_PREFIX is set to $BDB_PREFIX"

    - name: Set up Dependencies on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install -y msys2
        choco install -y mingw
        choco install -y nsis
        refreshenv
        msys2 -c "pacman -S --noconfirm base-devel mingw-w64-x86_64-toolchain"
        msys2 -c "echo 'export PATH=/mingw64/bin:$PATH' >> ~/.bashrc"
        msys2 -c "source ~/.bashrc"
        ./contrib/install_db4.sh $(pwd)
        export BDB_PREFIX=$(pwd)/db4
        echo "BDB_PREFIX is set to $BDB_PREFIX"

    - name: Set up Dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install autoconf automake libtool pkg-config boost openssl qt berkeley-db
        ./contrib/install_db4.sh $(pwd)
        export BDB_PREFIX=$(pwd)/db4
        echo "BDB_PREFIX is set to $BDB_PREFIX"

    - name: Configure and Build on Ubuntu for Windows
      if: matrix.os == 'ubuntu-18.04'
      run: |
        export BDB_PREFIX=$(pwd)/db4
        PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g') # Strip out problematic Windows %PATH% imported vars
        ./autogen.sh
        ./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include" --host=x86_64-w64-mingw32 --prefix=/usr/local --disable-tests --disable-gui-tests
        make
        make deploy

    - name: Configure and Build on macOS
      if: matrix.os == 'macos-latest'
      run: |
        export BDB_PREFIX=$(pwd)/db4
        export CXXFLAGS="-I$(brew --prefix berkeley-db@4)/include"
        export LDFLAGS="-L$(brew --prefix berkeley-db@4)/lib"
        ./autogen.sh
        ./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"
        make
        make deploy

    - name: Configure and Build on Windows
      if: matrix.os == 'windows-latest'
      shell: msys2 {0}
      run: |
        export BDB_PREFIX=$(pwd)/db4
        ./autogen.sh
        ./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include" --host=x86_64-w64-mingw32 --prefix=/usr/local --disable-tests --disable-gui-tests
        make
        make deploy

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: |
          osx/dist/Bitrae-Qt.app
          bitrae-0.1.0-win64-setup-unsigned.exe
          bitrae-0.1.0-linux-x86_64.tar.gz
